services:
  react-prod:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-reactjs-sample
    container_name: reactjs-sample-app-prod
    ports:
      - "8080:8080"

  react-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: docker-reactjs-sample-dev
    container_name: reactjs-sample-app-prod
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: sync
          path: .
          target: /app

  react-test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: docker-reactjs-sample-test
    container_name: reactjs-sample-app-test
    command: ["npm", "run", "test"]

  react-lint:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: docker-reactjs-sample-lint
    container_name: reactjs-sample-app-lint
    command: ["npm", "run", "lint"]
